version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - 3000:3000
    volumes: 
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on: 
      - adminer
      - db
    environment: 
      - HOST_DB=db
    command: npm run dev

  db:
    image: postgres
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: TaskManager
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db
